_extends: .github

repository:
  name: relazy
  description: ðŸ‘¤ Tool for lazy people to create new git releases
  homepage: https://nucleos.rocks
  topics: hacktoberfest, symfony, command, release, git, tag
